language: python
python:
  - '3.7'

branches:
    only:
        - staging

before_script:
  - pip install -r requirements.txt
    # - psql -c 'create database travis_ci_test;' -U postgres

env: DJANGO_SETTINGS_MODULE="platform_nutella.settings.__init__"

services:
  - postgresql

script:
  - python platform_nutella/manage.py test

