language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

branches:
    only:
        - staging

env: DJANGO_SETTINGS_MODULE="platform_nutella.settings.travis"

services:
  - postgresql

script:
  - platform_nutella/manage.py test

