language: python
python:
  - '3.7'

branches:
    only:
        - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="platform_nutella.settings.travis"

services:
  - postgresql

script:
  - python platform_nutella/manage.py test

